### ISSUE TITLE
clone failed

### ISSUE THREAD

**Issue by zhangliang1997** [HSA-on-FPGA/HSA-PacketProcessor#2]
Hi, i cloned mips compiler, but failed. 
The error is:
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by phholzinger** [comment]
As it seems that too many people downloaded this repository this month and since I cannot change the Git LFS plan, I temporarily uploaded the compilers to these locations:
https://faubox.rrze.uni-erlangen.de/getlink/fiXfn2npymwjVDDEQ9eidL3p/mips_gccs.tar.bz2
https://faubox.rrze.uni-erlangen.de/getlink/fi3gFNDKSsAaZrNfYGrNfM5y/gcc-mips64.tar.bz2

**Comment by zhangliang1997** [comment]
@phholzinger  Thanks very much 👍
